# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NodeJS Reports

on:
  workflow_run:
    workflows: ['NodeJS Build Process']
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Test Report
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results-20.x
        name: Mocha Tests
        path: test-results.xml
        reporter: jest-junit
        token: ${{ secrets.GIT_TOKEN }}

    - name: Coverage Report
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        artifact: coverage-results-20.x
        lcov-file: ./coverage/lcov.info
        token: ${{ secrets.GIT_TOKEN }}
